<?php
/**
 * ACF 主题设置字段
 *
 * @package SUBO4_Block_Theme
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( function_exists( 'acf_add_local_field_group' ) ):

acf_add_local_field_group(array(
    'key' => 'group_SUBO4_theme_settings',
    'title' => '主题设置',
    'fields' => array(
        array(
            'key' => 'field_SUBO4_profile_tab',
            'label' => '个人资料',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_SUBO4_avatar',
            'label' => '头像',
            'name' => 'SUBO4_avatar',
            'type' => 'image',
            'instructions' => '上传您的个人头像（建议尺寸：200x200像素）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_SUBO4_logo',
            'label' => '网站Logo',
            'name' => 'SUBO4_logo',
            'type' => 'image',
            'instructions' => '上传网站Logo（建议尺寸：高度40px，宽度自适应的长方形图片）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_SUBO4_author_name',
            'label' => '作者名称',
            'name' => 'SUBO4_author_name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'SUBO4',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_SUBO4_bio',
            'label' => '个人简介 / 签名',
            'name' => 'SUBO4_bio',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'All good things come to those who wait.',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_SUBO4_aboutme_content',
            'label' => '关于我内容',
            'name' => 'SUBO4_aboutme_content',
            'type' => 'textarea',
            'instructions' => '显示在文章详情页底部的"关于我"区块内容',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '张小璋，野蛮生长成世界500强企业供应链金融产品经理的法语毕业生。微信公众号：iamzhangsubo。一直在互联网金融公司从事产品经理工作并负责互联网金融产品线，深耕互联网金融和区块链领域。「PMCAFF」、「人人都是产品经理」专栏作家、「PmTalk」签约作家。',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_SUBO4_social_tab',
            'label' => '社交链接',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_SUBO4_github',
            'label' => 'GitHub 链接',
            'name' => 'SUBO4_github',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://github.com/username',
        ),
        array(
            'key' => 'field_SUBO4_twitter',
            'label' => 'Twitter 链接',
            'name' => 'SUBO4_twitter',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://twitter.com/username',
        ),
        array(
            'key' => 'field_SUBO4_facebook',
            'label' => 'Facebook 链接',
            'name' => 'SUBO4_facebook',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://facebook.com/username',
        ),
        array(
            'key' => 'field_SUBO4_email',
            'label' => '邮箱地址',
            'name' => 'SUBO4_email',
            'type' => 'email',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'hello@example.com',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_SUBO4_weibo',
            'label' => '微博链接',
            'name' => 'SUBO4_weibo',
            'type' => 'url',
            'instructions' => '输入微博个人主页链接',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://weibo.com/username',
        ),
        array(
            'key' => 'field_SUBO4_wechat_qr',
            'label' => '微信公众号二维码',
            'name' => 'SUBO4_wechat_qr',
            'type' => 'image',
            'instructions' => '上传微信公众号二维码图片（建议正方形）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_SUBO4_wechat_id_qr',
            'label' => '微信号二维码',
            'name' => 'SUBO4_wechat_id_qr',
            'type' => 'image',
            'instructions' => '上传个人微信号二维码图片（建议正方形）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_SUBO4_footer_tab',
            'label' => '页脚设置',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_SUBO4_icp_number',
            'label' => 'ICP 备案号',
            'name' => 'SUBO4_icp_number',
            'type' => 'text',
            'instructions' => '您的 ICP 备案号',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '津ICP备15001051号-2',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_SUBO4_complaints_email',
            'label' => '投诉举报邮箱',
            'name' => 'SUBO4_complaints_email',
            'type' => 'email',
            'instructions' => '用于接收违法和不良信息举报的邮箱地址',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'complaints@zhangsubo.cn',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'SUBO4-theme-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

endif;